version: "3.8"

services:

  postgres:
    image: postgres
    restart: always
    volumes:
    - postgres_files:/var/lib/postgresql/data
    ports:
      - "5454:5432"
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5050:80"

volumes:
  postgres_files:
    driver: local
